Implement methods to transactionally get and set multiple items
marcinwasowicz/localForage pull request #1
Opened 2024-07-26 17:26 UTC by marcinwasowicz

This PR modifies localforage to support transactional multiple item retrieval/persistence. The synchronizationKey and synchronizationValue arguments are used to handle race conditions. The setMultipleItems call will only succeed if current value under synchronizationKey in localforage is equal to expectedSynchronizationValue or forceWrite is set to true. This lets us select on thread to always win race condition.

Two methods mentioned above are implemented only for IndexedDB driver.

2024-07-31 15:09 UTC, xsanm commented on typings/localforage.d.ts
> +    setMultipleItems<T>(input: T, synchronizationKey: string, expectedSynchronizationValue?: string, newSynchronizationValue: string, forceWrite: boolean): Promise<void>;
I think the `T` here can be typed better, as we always expect this to be an object where keys are IndexedDB keys

2024-07-31 15:09 UTC, xsanm commented on typings/localforage.d.ts
> +    getMultipleItems<T>(keys: ReadonlyArray<keyof T>, synchronizationKey: string): Promise<Readonly<{...T, synchronizationValue?: string}>>;
```suggestion
    getMultipleItems<T>(keys: ReadonlyArray<keyof T>, synchronizationKey: string): Promise<Readonly<{value: T, synchronizationValue?: string}>>;
```

same as [here](https://phab.comm.dev/D12836#inline-74725) - we think that it's better and more readable than spreading

2024-07-31 15:09 UTC, xsanm commented on src/drivers/indexeddb.js
> +                        var requests = [];
I don't think we need this at all

2024-07-31 15:09 UTC, xsanm commented on src/drivers/indexeddb.js
> +                        var allKeys = [...normalizedKeys, synchronizationKey];
```suggestion
                        var allKeys = [...normalizedKeys, normalizedSynchronizationKey];
```

2024-07-31 15:09 UTC, xsanm commented on src/drivers/indexeddb.js
> +                                if (key === synchronizationKey) {
```suggestion
                                if (key === normalizedSynchronizationKey) {
```

2024-07-31 15:09 UTC, xsanm commented on src/drivers/indexeddb.js
> +                            requests.push(req);
what is this doing?

2024-07-31 15:09 UTC, xsanm commented on src/drivers/indexeddb.js
> +                                result['values'] = values;
this is different than the TS type - could you fix it? Also see suggestions about the type

2024-07-31 15:20 UTC, xsanm commented on src/drivers/indexeddb.js
> +                            });
You can just return `[normalizedKey, value]` without wrapping in `new Promise` and `Promise.all`  should handle this

2024-07-31 15:20 UTC, xsanm commented on src/drivers/indexeddb.js
> +                return inputNormalizationPromise;
```suggestion
                return Promise.all(
                    inputArray.map(function([key, value]) {
                        var normalizedKey = normalizeKey(key);
                        if (value === null) {
                            value = undefined;
                        }

                        if (!toString.call(value) === '[object Blob]') {
                            return new Promise(function(resolve, reject) {
                                resolve([normalizedKey, value]);
                            });
                        }

                        return _checkBlobSupport(dbInfo.db).then(function(
                            blobSupport
                        ) {
                            if (blobSupport) {
                                return [normalizedKey, value];
                            }
                            return [normalizedKey, _encodeBlob(value)];
                        });
                    })
                );
```

2024-07-31 15:20 UTC, xsanm commented on src/drivers/indexeddb.js
> +                        var writeRequests = [];
same as above - I don't think we need this

2024-07-31 15:20 UTC, xsanm commented on src/drivers/indexeddb.js
> +                            }
you not throwing - this is just calling `reject` callback, to make it work you should return here

2024-07-31 15:21 UTC, xsanm requested changes
Overall idea looks okay, requesting to address comments but those are mostly related to code quality, not to approach

2024-07-31 18:09 UTC, marcinwasowicz commented on typings/localforage.d.ts
> +    setMultipleItems<T>(input: T, synchronizationKey: string, expectedSynchronizationValue?: string, newSynchronizationValue: string, forceWrite: boolean): Promise<void>;
The `T` can be object with any keys so I am not sure how to make it more narrow. What do you mean by "object where keys are IndexedDB keys"?

2024-08-01 09:48 UTC, marcinwasowicz commented on src/drivers/indexeddb.js
> +                            requests.push(req);
As you suggested in one of previous comments it is probably not necessary and can be safely deleted.

2024-08-01 09:57 UTC, marcinwasowicz commented on src/drivers/indexeddb.js
> +                        var writeRequests = [];
We are creating those requests as local variables in a loop but we want their callback function to execute after the loop finishes. I was just worried that they might be garbage collected before their callbacks are called. I figured that putting them inside an array will prevent them from being garbage collected.

2024-08-01 09:57 UTC, marcinwasowicz commented on src/drivers/indexeddb.js
> +                        var writeRequests = [];
The reasoning was similar for `getMultipleItems`.

2024-08-01 12:17 UTC, xsanm approved these changes

2024-08-01 12:18 UTC, merged